/*
 * generated by Xtext 2.9.2
 */
package se.lth.cs.jastaddxtext.aspect.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import se.lth.cs.jastaddxtext.aspect.aspect.Model

@RunWith(XtextRunner)
@InjectWith(AspectInjectorProvider)
class AspectParsingTest{

	@Inject
	ParseHelper<Model> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
