/*
 * generated by Xtext 2.9.2
 */
package se.lth.cs.jastaddxtext.aspect

import org.eclipse.xtext.formatting.IFormatter
import se.lth.cs.jastaddxtext.aspect.formatting.Formatter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AspectRuntimeModule extends AbstractAspectRuntimeModule {
	override Class<? extends IFormatter> bindIFormatter() {
		return Formatter
	}
}