/*
 * generated by Xtext 2.9.0
 */
package se.lth.cs.jastaddxtext.javaRAG.ast

import se.lth.cs.jastaddxtext.javaRAG.ast.formatting.Formatter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AstRuntimeModule extends AbstractAstRuntimeModule {
	override Class<? extends org.eclipse.xtext.formatting.IFormatter> bindIFormatter() {
		return Formatter
	}
}
